# Generated by Django 4.1.3 on 2022-12-03 00:57

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tutorial_Title", models.CharField(max_length=200)),
                ("tutorial_Body", models.TextField()),
                ("tutorial_Video", embed_video.fields.EmbedVideoField()),
            ],
            options={"verbose_name_plural": "Tutorial",},
        ),
    ]
