# Generated by Django 4.1.3 on 2022-12-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_video_delete_tutorial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Video", new_name="Cardio_Video",),
    ]
