# Generated by Django 4.1.3 on 2022-12-03 04:51

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_rename_video_cardio_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strength_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("url", embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
