# Generated by Django 4.1.3 on 2022-12-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0009_quesmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuesModel",
        ),
    ]
