# Generated by Django 4.1.3 on 2022-12-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0012_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="blog-post-image"),
        ),
    ]
