# Generated by Django 4.1.3 on 2022-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0013_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dxzsuwkr7/image/upload/v1670138191/blog-post-image/what_jf6ur1.png",
                upload_to="blog-post-image",
            ),
        ),
    ]
